name: Test, lint, and build library

on: [push, pull_request]

jobs:
  test-library:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: python -m pipx install poetry

      - name: Install project
        run: poetry install

      - name: Test with tox
        run: poetry run tox

  test-deps:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: python -m pipx install poetry

      - name: Check pyproject.toml
        run: poetry check

      - name: Check if lockfile is updated
        run: poetry lock --check
